repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: ['-S']
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
    -   id: docformatter
        args: ['--in-place', '--wrap-summaries=80', '--wrap-descriptions=80', '--pre-summary-newline']
# -   repo: local
#     hooks:
#     -   id: flake8
#         name: flake8
#         description: wemade-python-styleguide
#         entry: flake8
#         args: ["--config=setup.cfg"]
#         language: python
#         types: [python]
#         # args: ['--ignore=Q000,W503']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: '214c33306afe17f1cc7d2d55e4da705b6ebe0627'
    hooks:
    -   id: mypy
